name: docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate documentation
        run: |
          mkdir -p dist
          cp README.md dist/index.md
          cp _config.yml dist/

      - name: Deploy to static branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: ${{ github.repository_owner }}
          user_email: '237133+0-vortex@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true
          cname: terraform.vortex.name
